language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

notifications:
  email: false
  slack:
    secure: Mo9p1sBTjlyZkD7U3eHT1vHeK2VbsbTpXgKYj+kj/kjTQJIT/wYLjJZ2yty8A9XMjZNG+MKaJIj66YcjrJ0jrW/n7c1ExAhMdC+D3bC8bNSovREH4gS2WGSBc/ALor4B6MCh2BUC17zgkmOTwttaJqjWL89ytmv4M3DHliYdojE=
