language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: SueBQDJp6PW3ta+RLF2+cWOpGhUzl/GLjhKuClFPA7qRsxWj8W6Sv9M6BdJdhykD/Q8PKO+fE+2+osVu9d3TaJb98+ImndWNsP0/MioDZZhnzh0/2UWyG66zHneHusdlYCd6cIs9C88Cvbu1J/9T/6rGWfgIi3JpalalO7e8dNw=
