defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  prepared_statements: false

development:
  <<: *defaults
  database: lektire_development

test:
  <<: *defaults
  database: lektire_test

staging:
  <<: *defaults
  database: lektire_staging

production:
  <<: *defaults
  database: lektire_production
