<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')
  suffix = `git config --bool branch.#{branch}.database`.chomp == 'true' ? "_#{branch}" : ""
%>

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: lektire_development<%= suffix %>

test:
  <<: *defaults
  database: lektire_test

staging:
  <<: *defaults
  database: lektire_staging

production:
  <<: *defaults
  database: lektire_production
