defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  <<: *defaults
  database: lektire_development

test:
  <<: *defaults
  database: lektire_test

production:
  <<: *defaults
  database: lektire_production
