namespace :db do
  task :migrate, [:version] do |task, args|
    sequel migrate: (args[:version] || true)
  end

  task :demigrate do
    sequel migrate: 0
  end

  task :remigrate => [:demigrate, :migrate]

  def sequel(migrate: nil)
    args = []

    if migrate
      args += %W[-m db/migrations]
      args += %W[-M #{migrate}] if Integer === migrate
    end

    args += %W[#{ENV["DATABASE_URL"] || "postgres:///kvizovi"}]

    sh ["sequel", *args].join(" ")
  end
end

task :console do
  ARGV.clear
  require "bundler/setup"
  require "kvizovi"
  require "pry"
  DB.transaction(rollback: :always) do
    Pry.start
  end
end
