namespace :db do
  desc "Runs the migrations (migrate to specific version with db:migrate[3])"
  task :migrate, :version do |task, args|
    command  = %W[sequel]
    command += %W[-m db/migrations]
    command += %W[-M #{args[:version]}] if args[:version]
    command += %W[config/database.yml]
    system *command
  end
end

task :console do
  system "bundle exec pry -r kvizovi"
end
